package model

// User represents an application user persisted in the "users" table.
//
// MIGRATION_NOTE: The Java source was a JPA @Entity mapped to a table named
// "USER" with mixed-case column names (User_id, User_name, ...). For the
// PostgreSQL target we use lower_snake_case identifiers so no quoting is
// required. Lombok's @Data/@Builder/@NoArgsConstructor/@AllArgsConstructor
// boilerplate is replaced by exported struct fields and the NewUser
// constructor. Bean Validation's @NotBlank(name) is expressed via a
// go-playground/validator struct tag.
//
// The ID is generated by the database (GENERATED ALWAYS AS IDENTITY / SERIAL),
// so it must be omitted on INSERT and populated via RETURNING id.
type User struct {
	// ID is the auto-generated primary key. It is assigned by the database
	// on insert and should not be set by callers.
	ID int `json:"id" db:"id"`

	// Name is the user's display name. It must not be blank.
	Name string `json:"name" db:"name" validate:"required"`

	// Email is the user's unique email address.
	Email string `json:"email" db:"email"`

	// Password is the user's (hashed) password.
	Password string `json:"password" db:"password"`

	// Role is the user's authorization role.
	Role string `json:"role" db:"role"`

	// About is a free-form description of the user (max 500 chars in source).
	About string `json:"about" db:"about" validate:"max=500"`
}

// NewUser constructs a User from the given fields. The ID is intentionally not
// a parameter because it is generated by the database on insert.
func NewUser(name, email, password, role, about string) *User {
	return &User{
		Name:     name,
		Email:    email,
		Password: password,
		Role:     role,
		About:    about,
	}
}
