```go
package model_test

import (
	"strings"
	"testing"

	"github.com/go-playground/validator/v10"
	"github.com/stretchr/testify/assert"

	"internal/smartcontact/model"
)

// validate is a package-level validator instance reused across tests.
var validate = validator.New()

// TestUserZeroValue verifies that a zero-value User has id=0 and all string
// fields empty (analogous to the Java no-arg constructor producing null
// reference fields and a default int for id).
func TestUserZeroValue(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		user model.User
		want model.User
	}{
		{
			name: "zero value user has id=0 and empty string fields",
			user: model.User{},
			want: model.User{
				ID:       0,
				Name:     "",
				Email:    "",
				Password: "",
				Role:     "",
				About:    "",
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tc.want.ID, tc.user.ID)
			assert.Equal(t, tc.want.Name, tc.user.Name)
			assert.Equal(t, tc.want.Email, tc.user.Email)
			assert.Equal(t, tc.want.Password, tc.user.Password)
			assert.Equal(t, tc.want.Role, tc.user.Role)
			assert.Equal(t, tc.want.About, tc.user.About)
		})
	}
}

// TestNewUser_AllFields verifies that NewUser populates every field correctly
// (all-args constructor equivalent).
func TestNewUser_AllFields(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		inName   string
		inEmail  string
		inPwd    string
		inRole   string
		inAbout  string
		wantUser model.User
	}{
		{
			name:    "all fields provided",
			inName:  "Alice",
			inEmail: "alice@example.com",
			inPwd:   "hashed_secret",
			inRole:  "ADMIN",
			inAbout: "Site administrator",
			wantUser: model.User{
				ID:       0, // DB-assigned, not set by NewUser
				Name:     "Alice",
				Email:    "alice@example.com",
				Password: "hashed_secret",
				Role:     "ADMIN",
				About:    "Site administrator",
			},
		},
		{
			name:    "empty optional fields",
			inName:  "Bob",
			inEmail: "",
			inPwd:   "",
			inRole:  "",
			inAbout: "",
			wantUser: model.User{
				ID:    0,
				Name:  "Bob",
				Email: "", Password: "", Role: "", About: "",
			},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := model.NewUser(tc.inName, tc.inEmail, tc.inPwd, tc.inRole, tc.inAbout)
			assert.NotNil(t, got)
			assert.Equal(t, tc.wantUser.ID, got.ID, "ID must be 0 – assigned by DB")
			assert.Equal(t, tc.wantUser.Name, got.Name)
			assert.Equal(t, tc.wantUser.Email, got.Email)
			assert.Equal(t, tc.wantUser.Password, got.Password)
			assert.Equal(t, tc.wantUser.Role, got.Role)
			assert.Equal(t, tc.wantUser.About, got.About)
		})
	}
}

// TestNewUser_IDNotSet verifies that NewUser never sets the ID field because
// the ID is generated by the database on INSERT.
func TestNewUser_IDNotSet(t *testing.T) {
	t.Parallel()

	u := model.NewUser("Carol", "carol@example.com", "pw", "USER", "About carol")
	assert.Equal(t, 0, u.ID, "NewUser must not set ID; it is assigned by the database")
}

// TestUser_PartialConstruction simulates the builder-pattern behaviour
// (specifying only some fields) by constructing a User struct literal with
// only a subset of fields.
func TestUser_PartialConstruction(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		user     model.User
		wantID   int
		wantName string
		wantRole string
	}{
		{
			name:     "only name and role set",
			user:     model.User{Name: "Dave", Role: "MOD"},
			wantID:   0,
			wantName: "Dave",
			wantRole: "MOD",
		},
		{
			name:     "only email set",
			user:     model.User{Email: "eve@example.com"},
			wantID:   0,
			wantName: "",
			wantRole: "",
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tc.wantID, tc.user.ID)
			assert.Equal(t, tc.wantName, tc.user.Name)
			assert.Equal(t, tc.wantRole, tc.user.Role)
		})
	}
}

// TestUser_SetterGetterEquivalent verifies that writing a field and reading it
// back returns the value that was written (setter/getter round-trip).
func TestUser_SetterGetterEquivalent(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name      string
		field     string
		applyFunc func(*model.User)
		readFunc  func(*model.User) interface{}
		want      interface{}
	}{
		{
			name:      "set and get Name",
			field:     "Name",
			applyFunc: func(u *model.User) { u.Name = "Frank" },
			readFunc:  func(u *model.User) interface{} { return u.Name },
			want:      "Frank",
		},
		{
			name:      "set and get Email",
			field:     "Email",
			applyFunc: func(u *model.User) { u.Email = "frank@example.com" },
			readFunc:  func(u *model.User) interface{} { return u.Email },
			want:      "frank@example.com",
		},
		{
			name:      "set and get Password",
			field:     "Password",
			applyFunc: func(u *model.User) { u.Password = "supersecret" },
			readFunc:  func(u *model.User) interface{} { return u.Password },
			want:      "supersecret",
		},
		{
			name:      "set and get Role",
			field:     "Role",
			applyFunc: func(u *model.User) { u.Role = "EDITOR" },
			readFunc:  func(u *model.User) interface{} { return u.Role },
			want:      "EDITOR",
		},
		{
			name:      "set and get About",
			field:     "About",
			applyFunc: func(u *model.User) { u.About = "Short bio" },
			readFunc:  func(u *model.User) interface{} { return u.About },
			want:      "Short bio",
		},
		{
			name:      "set and get ID",
			field:     "ID",
			applyFunc: func(u *model.User) { u.ID = 42 },
			readFunc:  func(u *model.User) interface{} { return u.ID },
			want:      42,
		},
		{
			name: "overwrite Name twice keeps last value",
			field: "Name",
			applyFunc: func(u *model.User) {
				u.Name = "First"
				u.Name = "Second"
			},
			readFunc: func(u *model.User) interface{} { return u.Name },
			want:     "Second",
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			u := &model.User{}
			tc.applyFunc(u)
			got := tc.readFunc(u)
			assert.Equal(t, tc.want, got)
		})
	}
}

// TestUser_Validation_Name exercises the `validate:"required"` tag on Name.
func TestUser_Validation_Name(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name        string
		user        model.User
		wantValid   bool
		errContains string
	}{
		{
			name:      "valid name passes validation",
			user:      model.User{Name: "Grace", About: "hello"},
			wantValid: true,
		},
		{
			name:        "empty name fails required validation",
			user:        model.User{Name: "", About: "hello"},
			wantValid:   false,
			errContains: "Name",
		},
		{
			name:        "whitespace-only name fails required validation",
			user:        model.User{Name: "   ", About: "hello"},
			wantValid:   false,
			errContains: "Name",
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			err := validate.Struct(tc.user)
			if tc.wantValid {
				assert.NoError(t, err)
			} else {
				assert.Error(t, err)
				if tc.errContains != "" {
					assert.Contains(t, err.Error(), tc.errContains)
				}
			}
		})
	}
}

// TestUser_Validation_About exercises the `validate:"max=500"` tag on About.
func TestUser_Validation_About(t *testing.T) {
	t.Parallel()

	exactly500 := strings.Repeat("a", 500)
	over500 := strings.Repeat("b", 501)

	tests := []struct {
		name      string
		user      model.User
		wantValid bool
	}{
		{
			name:      "about exactly 500 chars passes",
			user:      model.User{Name: "Henry", About: exactly500},
			wantValid: true,
		},
		{
			name:      "about under 500 chars passes",
			user:      model.User{Name: "Henry", About: "Short bio"},
			wantValid: true,
		},
		{
			name:      "about empty string passes",
			user:      model.User{Name: "Henry", About: ""},
			wantValid: true,
		},
		{
			name:      "about 501 chars fails max=500",
			user:      model.User{Name: "Henry", About: over500},
			wantValid: false,
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			err := validate.Struct(tc.user)
			if tc.wantValid {
				assert.NoError(t, err)
			} else {
				assert.Error(t, err)
				assert.Contains(t, err.Error(), "About")
			}
		})
	}
}

// TestUser_Equality verifies that two User instances with identical field
// values compare equal (mirrors Lombok @Data equals/hashCode behaviour).
func TestUser_Equality(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name      string
		a         model.User
		b         model.User
		wantEqual bool
	}{
		{
			name: "identical users are equal",
			a:    model.User{ID: 1, Name: "Ivy", Email: "ivy@example.com", Password: "pw", Role: "USER", About: "bio"},
			b:    model.User{ID: 1, Name: "Ivy", Email: "ivy@example.com", Password: "pw", Role: "USER", About: "bio"},
			wantEqual: true,
		},
		{
			name:      "zero value users are equal",
			a:         model.User{},
			b:         model.User{},
			wantEqual: true,
		},
		{
			name:      "users differing only in ID are not equal",
			a:         model.User{ID: 1, Name: "Jack"},
			b:         model.User{ID: 2, Name: "Jack"},
			wantEqual: false,
		},
		{
			name:      "users differing in Name are not equal",
			a:         model.User{ID: 1, Name: "Jack"},
			b:         model.User{ID: 1, Name: "Jill"},
			wantEqual: false,
		},
		{
			name:      "users differing in Email are not equal",
			a:         model.User{ID: 1, Name: "Jack", Email: "a@example.com"},
			b:         model.User{ID: 1, Name: "Jack", Email: "b@example.com"},
			wantEqual: false,
		},
		{
			name:      "users differing in Role are not equal",
			a:         model.User{ID: 1, Name: "Jack", Role: "ADMIN"},
			b:         model.User{ID: 1, Name: "Jack", Role: "USER"},
			wantEqual: false,
		},
		{
			name:      "users differing in About are not equal",
			a:         model.User{ID: 1, Name: "Jack", About: "bio A"},
			b:         model.User{ID: 1, Name: "Jack", About: "bio B"},
			wantEqual: false,
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if tc.wantEqual {
				assert.Equal(t, tc.a, tc.b)
			} else {
				assert.NotEqual(t, tc.a, tc.b)
			}
		})
	}
}

// TestUser_StringRepresentation verifies that a User's fields are accessible
// and can be used to construct a meaningful string (analogous to Lombok
// @Data toString including all field names and values).
func TestUser_StringRepresentation(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		user         model.User
		wantContains []string
	}{
		{
			name: "toString-like representation contains all field values",
			user: model.User{
				ID:       7,
				Name:     "Karen",
				Email:    "karen@example.com",
				Password: "hashed",
				Role:     "VIEWER",
				About:    "Karen's bio",
			},
			wantContains: []string{"Karen", "karen@example.com", "hashed", "VIEWER", "Karen's bio"},
		},
	}

	for _, tc := range tests {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			// Build a string representation using all fields, mirroring what
			// Lombok's toString would produce.
			repr := strings.Join([]string{
				tc.user.Name,
				tc.user.Email,
				tc.user.Password,
				