// Package model contains the domain entities and data transfer objects (DTOs)
// used by the SmartContact service.
//
// MIGRATION_NOTE: The Java source User.java was a JPA @Entity mapping the USER
// table, decorated with Lombok (@Data, @NoArgsConstructor, @AllArgsConstructor,
// @Builder) and Bean Validation (@NotBlank). Go has no annotation-driven ORM or
// validation. The idiomatic translation is a plain struct with:
//
//   - `db` struct tags describing the physical column names, consumable by
//     database/sql helpers such as sqlx (Hibernate/JPA has no direct Go
//     equivalent; explicit SQL or a lightweight mapper is preferred).
//   - `json` struct tags for API (de)serialization.
//   - `validate` struct tags for github.com/go-playground/validator/v10, which
//     replaces javax.validation. The @NotBlank on `name` becomes
//     `validate:"required"`.
//
// Lombok's generated getters, setters, equals, hashCode, toString and Builder
// are unnecessary in idiomatic Go: exported fields are accessed directly, value
// equality is provided by the language for comparable structs, and construction
// uses either a struct literal or the NewUser constructor below.
//
// MANUAL REVIEW:
//   - JPA's @GeneratedValue(strategy = AUTO) delegated primary-key generation to
//     Hibernate. In Go the ID is expected to be assigned by the database
//     (e.g. an AUTO_INCREMENT / SERIAL column) and read back after INSERT, or
//     generated by the repository layer. The zero value (0) denotes an
//     unpersisted User.
//   - The @Column(unique = true) constraint on Email must be enforced at the
//     schema level (a UNIQUE index); it is documented here but not something the
//     struct itself can guarantee.
package model

import (
	"github.com/go-playground/validator/v10"
)

// User is the domain entity for an application user. It maps to the USER table.
//
// The original JPA column mappings are preserved via the `db` struct tags so
// that a data-access layer can bind rows without magic. Validation rules mirror
// the Bean Validation annotations from the Java source.
type User struct {
	// ID is the primary key (USER.User_id). A value of 0 indicates a User that
	// has not yet been persisted; the database assigns the real value on insert.
	ID int `json:"id" db:"User_id"`

	// Name is the user's display name (USER.User_name). It is required — this
	// corresponds to the Java @NotBlank(message = "please Add the department Name").
	Name string `json:"name" db:"User_name" validate:"required"`

	// Email is the user's email address (USER.User_Email). It must be unique at
	// the database level (@Column unique = true in the original entity).
	Email string `json:"email" db:"User_Email"`

	// Password is the user's (hashed) password (USER.User_Password).
	Password string `json:"password" db:"User_Password"`

	// Role is the user's authorization role (USER.User_Role).
	Role string `json:"role" db:"User_Role"`

	// About is a free-text description of the user (USER.User_About), limited to
	// 500 characters in the original schema.
	About string `json:"about" db:"User_About" validate:"max=500"`
}

// NewUser constructs a User from the supplied field values. It mirrors the
// Lombok @AllArgsConstructor but leaves the ID at its zero value, since the
// primary key is assigned by the persistence layer on insert.
func NewUser(name, email, password, role, about string) *User {
	return &User{
		Name:     name,
		Email:    email,
		Password: password,
		Role:     role,
		About:    about,
	}
}

// Validate checks the User against its Bean-Validation-equivalent rules using
// go-playground/validator. It returns a non-nil error describing the first (or
// aggregated) constraint violation, or nil when the User is valid.
//
// MIGRATION_NOTE: In the Spring application these constraints were enforced
// automatically by @Valid on the controller method argument. In Go the check is
// explicit; the SaveUserData handler is expected to call Validate before
// persisting (see Change 14).
func (u *User) Validate(v *validator.Validate) error {
	if v == nil {
		v = validator.New()
	}
	return v.Struct(u)
}
