// Package smartcontact contains the SmartContact service and its tests.
// It is the Go equivalent of the Java package com.smartContact.
//
// MIGRATION_NOTE: The source SmartContactApplicationTests.java was the
// default Spring Boot integration test generated by Spring Initializr.
// The single @SpringBootTest annotation, with an empty test body, only
// verified that the Spring application context could be constructed and
// wired successfully at startup (the implicit "contextLoads" check).
//
// Go has no equivalent to Spring's dependency-injection container, so
// there is no "application context" to boot. The idiomatic Go analogue
// is a smoke test that exercises the application's own wiring/constructor
// path and asserts it succeeds without error. Below we build the same
// configuration and core domain objects that the real application would
// assemble, verifying they initialize cleanly.
//
// This is a table-driven test file (the *_test.go convention). If it were
// intended to be non-test production code, the constructors from the
// migrated packages should be composed in a main/wire entrypoint instead.
package smartcontact

import (
	"testing"

	"github.com/smartContact/internal/resources"
	"github.com/smartContact/internal/smartcontact/model"
)

// TestContextLoads is the Go equivalent of the implicit Spring Boot
// "contextLoads" check. Rather than booting a DI container, it verifies
// that the application's configuration and core domain constructors
// assemble successfully, which is the closest idiomatic analogue.
//
// MIGRATION_NOTE: Replace the wiring exercised here with the actual
// application bootstrap (e.g. a NewServer/NewApp constructor) once it
// exists, so this smoke test tracks the real startup path.
func TestContextLoads(t *testing.T) {
	tests := []struct {
		name string
		run  func(t *testing.T)
	}{
		{
			name: "config initializes with defaults",
			run: func(t *testing.T) {
				cfg := resources.NewConfig()
				if cfg == nil {
					t.Fatal("NewConfig returned nil")
				}
				if addr := cfg.Addr(); addr == "" {
					t.Error("Config.Addr() returned empty string")
				}
				if dsn := cfg.DSN(); dsn == "" {
					t.Error("Config.DSN() returned empty string")
				}
			},
		},
		{
			name: "core domain objects construct without error",
			run: func(t *testing.T) {
				u := model.NewUser()
				if u == nil {
					t.Fatal("NewUser returned nil")
				}
				if em := model.NewErrorMessage(0, ""); em == nil {
					t.Fatal("NewErrorMessage returned nil")
				}
			},
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			tt.run(t)
		})
	}
}
